name: coordn8r
description: Application to facilitate all aspects of teamwork, collaboration, and coordination.

dependencies:
  community_material_icon: "^0.1.2"

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  # Allows access to the firestore storage in firebase for backend
  cloud_firestore: ^0.7.2

  # Firebase authentication
  firebase_auth: "^0.5.11"

  # Google sign in capabilities
  google_sign_in: "^3.0.4"


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/logo/logo192.png
   - assets/logo/logo144.png
   - assets/logo/logo96.png
   - assets/logo/logo72.png
   - assets/logo/logo48.png
   - assets/logo/logo192_1.png
   - assets/logo/logo192_2.png
   - assets/logo/logo192_3.png
   - assets/logo/logo144_1.png
   - assets/logo/logo144_2.png
   - assets/logo/logo144_3.png
   - assets/logo/logo96_1.png
   - assets/logo/logo96_2.png
   - assets/logo/logo96_3.png
   - assets/logo/logo72_1.png
   - assets/logo/logo72_2.png
   - assets/logo/logo72_3.png
   - assets/logo/logo48_1.png
   - assets/logo/logo48_2.png
   - assets/logo/logo48_3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
